# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  vm-executor:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    environment:
      shell: /bin/bash
      TERM: xterm
      TZ: "Europe/Berlin"

workflows:
  test-workflow:
    jobs:
      - test-job

commands:
  say-hello-with-ssh:
    description: "Say hello with ssh"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ba:fc:ed:ea:ba:be:ce:75:a8:cf:11:bb:99:9d:d2:54"
      - run:
          shell: /bin/bash
          name: clone-repo
          command: >-
            ssh arkocal@82.165.71.183 "echo Building on external server &&
            echo ${CIRCLE_REPOSITORY_URL} &&
            mkdir /tmp/${CIRCLE_JOB}_${CIRCLE_BUILD_NUM} &&
            cd /tmp/${CIRCLE_JOB}_${CIRCLE_BUILD_NUM} &&
            git clone ${CIRCLE_REPOSITORY_URL} -b ${CIRCLE_BRANCH}"
      - run:
          shell: /bin/bash
          name: build
          command: >-
            ssh arkocal@82.165.71.183
            "cd /tmp/${CIRCLE_JOB}_${CIRCLE_BUILD_NUM}/${CIRCLE_PROJECT_REPONAME}/public-interface &&
            docker build . -t oisp/frontend:${CIRCLE_BUILD_NUM}"
jobs:
  test-job:
    executor: vm-executor
    steps:
      - say-hello-with-ssh
